"""Initial schema

Revision ID: 14710c2fc6ad
Revises: 9ad508746f73
Create Date: 2026-08-19 15:34:18.111661
"""

from __future__ import annotations

from collections.abc import Sequence

# revision identifiers
revision: str = "14710c2fc6ad"
down_revision: str | None = "9ad508746f73"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
